### PR TITLE
Put RUNPATH before LD_LIBRARY_PATH

### PR DESCRIPTION
**Pull request by rmcgibbo**
@njsmith: I think this might fix the issue on your platform with pyside (?). The linker searches RPATH, then LD_LIBRARY_PATH, then RUNPATH, but for the purpose of determining what libs to copy into the wheel, as you pointed out by email, it makes more sense to search RUNPATH first.

### CODE REVIEW

**Comment by njsmith** [comment]
huh, out of curiosity why are we patching RUNPATH instead of RPATH?

On Sun, Jan 17, 2016 at 10:33 PM, Robert T. McGibbon <
notifications@github.com> wrote:

> @njsmith <https://github.com/njsmith>: I think this might fix the issue
> on your platform with pyside (?). The linker searches RPATH, then
> LD_LIBRARY_PATH, then RUNPATH, but for the purpose of determining what libs
> to copy into the wheel, as you pointed out by email, it makes more sense to
> search RUNPATH first.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/manylinux/auditwheel/pull/4
> Commit Summary
>
>    - Put RUNPATH before LD_LIBRARY_PATH
>
> File Changes
>
>    - *M* auditwheel/lddtree.py
>    <https://github.com/manylinux/auditwheel/pull/4/files#diff-0> (6)
>    - *M* auditwheel/main_show.py
>    <https://github.com/manylinux/auditwheel/pull/4/files#diff-1> (3)
>    - *M* auditwheel/repair.py
>    <https://github.com/manylinux/auditwheel/pull/4/files#diff-2> (2)
>
> Patch Links:
>
>    - https://github.com/manylinux/auditwheel/pull/4.patch
>    - https://github.com/manylinux/auditwheel/pull/4.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/manylinux/auditwheel/pull/4>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by rmcgibbo** [comment]
We're not patching RUNPATH. The Qt binaries include a RUNPATH record.

**Comment by njsmith** [comment]
Oh, interesting! From what I'm reading, if RUNPATH is set then RPATH is
ignored, so if they already include a RUNPATH then could our patching fail
to be effective?

On Sun, Jan 17, 2016 at 11:15 PM, Robert T. McGibbon <
notifications@github.com> wrote:

> Merged #4 <https://github.com/manylinux/auditwheel/pull/4>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/manylinux/auditwheel/pull/4#event-517603530>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by rmcgibbo** [comment]
Not quite. In this case the Qt binaries have a RUNPATH set to $ORIGIN/. Our patching was adding a RPATH of $ORIGIN/, so it's really no change.

But the issue, I think, was that since LD_LIBRARY_PATH comes before RUNPATH in resolution order, some of the libraries all in the same directory that were linked to each other were actually resolving to libraries in LD_LIBRARY_PATH in your example.

**Pull request merged**
